/**
 * Gestures module - detects and streams user gestures using RxJS.
 * Ported from ChronoZoom's gestures.js with modern RxJS v7 and native DOM events.
 */

import { Observable, fromEvent, merge } from 'rxjs';
import { map, switchMap, takeUntil, pairwise } from 'rxjs/operators';
import { ChronoCanvasOptions } from './types';

/**
 * Gesture type discriminator
 */
export type GestureType = 'Pan' | 'Zoom' | 'Pin';

/**
 * Base interface for all gestures
 */
export interface Gesture {
  readonly Type: GestureType;
  readonly Source: 'Mouse';
}

/**
 * Pan gesture - indicates viewport translation.
 * Generated during mouse drag operations.
 */
export interface PanGesture extends Gesture {
  readonly Type: 'Pan';
  /** Horizontal offset in screen pixels (positive = moved left, negative = moved right) */
  readonly xOffset: number;
  /** Vertical offset in screen pixels (positive = moved up, negative = moved down) */
  readonly yOffset: number;
}

/**
 * Zoom gesture - indicates scale change at a point.
 * Generated by mouse wheel events.
 */
export interface ZoomGesture extends Gesture {
  readonly Type: 'Zoom';
  /** X position of zoom origin in screen coordinates */
  readonly xOrigin: number;
  /** Y position of zoom origin in screen coordinates */
  readonly yOrigin: number;
  /** Scale multiplication factor (>1 = zoom in, <1 = zoom out) */
  readonly scaleFactor: number;
}

/**
 * Pin gesture - indicates start of interaction (stops animations).
 * Generated when mouse button is pressed.
 */
export interface PinGesture extends Gesture {
  readonly Type: 'Pin';
  /** Cursor X position in canvas pixels at mousedown */
  readonly xPos: number;
  /** Cursor Y position in canvas pixels at mousedown */
  readonly yPos: number;
}

/**
 * Creates a pan gesture stream from mouse drag events.
 * Detects pan gestures from mouse drag operations.
 * 
 * @param element - Element to observe for pan gestures
 * @returns Observable stream of pan gestures
 * 
 * @remarks
 * A pan gesture is created when:
 * 1. User presses mouse button down
 * 2. User moves mouse while button is held
 * 3. Stream continues until mouse button is released
 */
function createPanGestureStream(element: HTMLElement): Observable<PanGesture> {
  const mouseDown$ = fromEvent<MouseEvent>(element, 'mousedown');
  const mouseMove$ = fromEvent<MouseEvent>(element, 'mousemove');
  const mouseUp$ = fromEvent<MouseEvent>(document, 'mouseup');
  
  return mouseDown$.pipe(
    switchMap(() =>
      mouseMove$.pipe(
        pairwise(),
        map(([prev, curr]) => ({
          Type: 'Pan' as const,
          Source: 'Mouse' as const,
          xOffset: prev.clientX - curr.clientX,
          yOffset: prev.clientY - curr.clientY
        })),
        takeUntil(mouseUp$)
      )
    )
  );
}

/**
 * Creates a pin gesture stream from mouse down events.
 * Detects when user begins interaction.
 * 
 * @param element - Element to observe for pin gestures
 * @returns Observable stream of pin gestures
 * 
 * @remarks
 * Pin gestures are used to stop ongoing animations when user begins interaction.
 */
function createPinGestureStream(element: HTMLElement): Observable<PinGesture> {
  const mouseDown$ = fromEvent<MouseEvent>(element, 'mousedown');
  
  return mouseDown$.pipe(
    map(event => {
      const rect = element.getBoundingClientRect();
      return {
        Type: 'Pin' as const,
        Source: 'Mouse' as const,
        xPos: event.clientX - rect.left,
        yPos: event.clientY - rect.top
      };
    })
  );
}

/**
 * Creates a zoom gesture stream from mouse wheel events.
 * Detects zoom gestures from mouse wheel operations.
 * 
 * @param element - Element to observe for zoom gestures (receives wheel events)
 * @param coordinateElement - Element whose coordinate system to use (typically container matching viewport)
 * @param settings - Configuration for zoom sensitivity
 * @returns Observable stream of zoom gestures
 * 
 * @remarks
 * Uses clientX/clientY with coordinateElement's rect for robust coordinates
 * that match the viewport coordinate system.
 */
function createZoomGestureStream(
  element: HTMLElement,
  coordinateElement: HTMLElement,
  settings: Required<ChronoCanvasOptions>
): Observable<ZoomGesture> {
  const wheel$ = fromEvent<WheelEvent>(element, 'wheel');
  
  return wheel$.pipe(
    // Prevent default browser zoom behavior
    map(event => {
      event.preventDefault();
      return event;
    }),
    map(event => {
      // Determine zoom direction from deltaY
      // Negative deltaY = scroll up = zoom in
      // Positive deltaY = scroll down = zoom out
      const scaleFactor = event.deltaY < 0 
        ? 1 / settings.zoomLevelFactor  // Zoom in
        : settings.zoomLevelFactor;      // Zoom out
      // Use offsetX/offsetY - position relative to event target (canvas)
      const rect = coordinateElement.getBoundingClientRect();
      const xOrigin = 'offsetX' in event && typeof (event as MouseEvent).offsetX === 'number'
        ? (event as MouseEvent).offsetX
        : event.clientX - rect.left;
      const yOrigin = 'offsetY' in event && typeof (event as MouseEvent).offsetY === 'number'
        ? (event as MouseEvent).offsetY
        : event.clientY - rect.top;
      return {
        Type: 'Zoom' as const,
        Source: 'Mouse' as const,
        xOrigin,
        yOrigin,
        scaleFactor
      };
    })
  );
}

/**
 * Creates a reactive stream of user gestures from DOM events.
 * Combines pan, zoom, and pin gesture streams into a single observable.
 * 
 * Only responsible for gesture detection.
 * Does not handle viewport updates or animations (that's the controller's job).
 * 
 * @param element - The HTML element to observe for gestures
 * @param settings - Configuration for gesture sensitivity
 * @returns Observable stream emitting pan, zoom, and pin gestures
 * 
 * @example
 * ```typescript
 * const gestures$ = createGestureStream(canvasElement, settings);
 * gestures$.subscribe(gesture => {
 *   switch (gesture.Type) {
 *     case 'Pan':
 *       viewport.pan(gesture.xOffset, gesture.yOffset);
 *       break;
 *     case 'Zoom':
 *       viewport.zoom(gesture.xOrigin, gesture.yOrigin, gesture.scaleFactor);
 *       break;
 *     case 'Pin':
 *       stopAnimations();
 *       break;
 *   }
 * });
 * ```
 */
export function createGestureStream(
  element: HTMLElement,
  containerOrSettings: HTMLElement | Required<ChronoCanvasOptions>,
  settings?: Required<ChronoCanvasOptions>
): Observable<PanGesture | ZoomGesture | PinGesture> {
  // (element, container, settings) or (element, settings) for backward compat
  const coordEl = containerOrSettings instanceof HTMLElement ? containerOrSettings : element;
  const opts = (settings ?? containerOrSettings) as Required<ChronoCanvasOptions>;
  const pan$ = createPanGestureStream(element);
  const zoom$ = createZoomGestureStream(element, coordEl, opts);
  const pin$ = createPinGestureStream(element);
  
  // Merge all gesture streams into one
  return merge(pan$, zoom$, pin$);
}
